"""empty message

Revision ID: 0c69ac161451
Revises: 9d164b80e40d
Create Date: 2018-05-14 09:09:32.938811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c69ac161451'
down_revision = '9d164b80e40d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queryplans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('queryplan_name', sa.String(), nullable=True),
    sa.Column('phraselist_name', sa.String(), nullable=True),
    sa.Column('hlct_name', sa.String(), nullable=True),
    sa.Column('referto', sa.String(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('crud', sa.SmallInteger(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('queryplans')
    # ### end Alembic commands ###
