"""empty message

Revision ID: 9274ebedd7bf
Revises: 
Create Date: 2018-06-08 10:03:42.167762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9274ebedd7bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pkey', sa.String(length=100), nullable=True),
    sa.Column('parent_pkey', sa.String(length=100), nullable=True),
    sa.Column('json_content', sa.Text(), nullable=True),
    sa.Column('type_code', sa.Integer(), nullable=True),
    sa.Column('lastupdate_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('surveyscores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.String(length=10), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('lastupdate_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('surveyscores')
    op.drop_table('surveys')
    # ### end Alembic commands ###
