"""empty message

Revision ID: 9d164b80e40d
Revises: b27a9a7daeb4
Create Date: 2018-05-13 08:41:19.332426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d164b80e40d'
down_revision = 'b27a9a7daeb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marklogics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('filepath', sa.String(), nullable=True),
    sa.Column('referto', sa.String(), nullable=True),
    sa.Column('epoch', sa.String(), nullable=True),
    sa.Column('phraselist_name', sa.String(), nullable=True),
    sa.Column('failed', sa.SmallInteger(), nullable=True),
    sa.Column('success', sa.SmallInteger(), nullable=True),
    sa.Column('total', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('crud', sa.SmallInteger(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marklogics')
    # ### end Alembic commands ###
