"""empty message

Revision ID: 9d44a3302bad
Revises: 0c69ac161451
Create Date: 2018-05-16 06:39:22.907382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d44a3302bad'
down_revision = '0c69ac161451'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marklogics', sa.Column('env', sa.SmallInteger(), nullable=True))
    op.add_column('queryplans', sa.Column('env', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queryplans', 'env')
    op.drop_column('marklogics', 'env')
    # ### end Alembic commands ###
