"""empty message

Revision ID: b27a9a7daeb4
Revises: 8e615c208ab6
Create Date: 2018-04-24 05:20:27.165949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b27a9a7daeb4'
down_revision = '8e615c208ab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comparisons', sa.Column('comparison_name', sa.String(), nullable=True))
    op.add_column('comparisons', sa.Column('full_score', sa.String(), nullable=True))
    op.add_column('comparisons', sa.Column('partial_score', sa.String(), nullable=True))
    op.add_column('comparisons', sa.Column('total', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comparisons', 'total')
    op.drop_column('comparisons', 'partial_score')
    op.drop_column('comparisons', 'full_score')
    op.drop_column('comparisons', 'comparison_name')
    # ### end Alembic commands ###
