"""empty message

Revision ID: d11a2c784556
Revises: 
Create Date: 2018-05-29 02:37:12.504549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd11a2c784556'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comparisons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comparison_name', sa.String(), nullable=True),
    sa.Column('analysis_filename', sa.String(), nullable=True),
    sa.Column('analysis_filepath', sa.String(), nullable=True),
    sa.Column('manual_filename', sa.String(), nullable=True),
    sa.Column('manual_filepath', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('score', sa.String(), nullable=True),
    sa.Column('full_score', sa.String(), nullable=True),
    sa.Column('partial_score', sa.String(), nullable=True),
    sa.Column('total', sa.SmallInteger(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('engine_id', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marklogics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('filepath', sa.String(), nullable=True),
    sa.Column('referto', sa.String(), nullable=True),
    sa.Column('epoch', sa.String(), nullable=True),
    sa.Column('phraselist_name', sa.String(), nullable=True),
    sa.Column('failed', sa.SmallInteger(), nullable=True),
    sa.Column('success', sa.SmallInteger(), nullable=True),
    sa.Column('total', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('crud', sa.SmallInteger(), nullable=True),
    sa.Column('env', sa.SmallInteger(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('segmentation', sa.String(), nullable=True),
    sa.Column('engine_id', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queryplans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('queryplan_name', sa.String(), nullable=True),
    sa.Column('phraselist_name', sa.String(), nullable=True),
    sa.Column('hlct_name', sa.String(), nullable=True),
    sa.Column('referto', sa.String(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('crud', sa.SmallInteger(), nullable=True),
    sa.Column('env', sa.SmallInteger(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('surveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('json_content', sa.String(), nullable=True),
    sa.Column('lastupdate_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('surveyscores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.String(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('lastupdate_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('files_queries',
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('query_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['query_id'], ['queries.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files_queries')
    op.drop_table('surveyscores')
    op.drop_table('surveys')
    op.drop_table('queryplans')
    op.drop_table('queries')
    op.drop_table('marklogics')
    op.drop_table('files')
    op.drop_table('comparisons')
    # ### end Alembic commands ###
